#!/bin/bash

ECLIPSE_LOC=~/bin/eclipse/
export SLOBER_LOC=$ECLIPSE_LOC

ZIP=Eclipse-Macos.zip
if [[ $(uname -m) == 'arm64' ]]; then
  echo "M1 Mac detected " 
  ZIP=Eclipse-mac-AArch64.zip
fi

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


if (! test -e ~/bin) then
 mkdir ~/bin
fi

if ! [ "$SCRIPT" = "$HOME/bin" ]; then
 echo "Script source copied to ~/bin from " $SCRIPT
 cp $SCRIPT/eclipse-mac ~/bin/eclipse-mac
 chmod +x  ~/bin/eclipse-mac
fi


if (! test -e $ECLIPSE_LOC) then
  if (! test -e ~/bin/$ZIP ) then
	 curl  -L https://github.com/CommonWealthRobotics/ESP32ArduinoEclipseInstaller/releases/download/0.0.0/$ZIP -o ~/bin/$ZIP
  fi
  echo "$ECLIPSE_LOC not found, unzipping Eclipse... "
  unzip ~/bin/$ZIP  -qq -d $SLOBER_LOC
  echo "unzipping Eclipse... Complete!ß "


fi

cd $SLOBER_LOC; grep -RiIl 'kharrington' .| xargs sed -i '' -e "s/kharrington/$USER/g"

echo "Parameters are $@"
#Run SLoeber
open $SLOBER_LOC/Eclipse.app --args "$@"
#$SLOBER_LOC/Eclipse.app/Contents/MacOS/eclipse "$@"
#open $SLOBER_LOC/Eclipse.app --args -import {"$@"}


