#!/bin/bash

ECLIPSE_LOC=~/bin/eclipse/
export SLOBER_LOC=$ECLIPSE_LOC

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


if (! test -e ~/bin) then
 mkdir ~/bin
fi

if ! [ "$SCRIPT" = "$HOME/bin" ]; then
 echo "Script source copied to ~/bin from " $SCRIPT
 cp $SCRIPT/eclipse-mac ~/bin/eclipse-mac
 chmod +x  ~/bin/eclipse-mac
fi


if (! test -e $ECLIPSE_LOC) then
  if (! test -e ~/bin/linux-sloeber-eclipse.zip ) then
	 curl  -L https://github.com/CommonWealthRobotics/ESP32ArduinoEclipseInstaller/releases/download/0.0.0/Eclipse-Macos.zip -o ~/bin/Eclipse-Macos.zip
	fi
	
	unzip ~/bin/Eclipse-Macos.zip -d $SLOBER_LOC

fi

cd $SLOBER_LOC; grep -RiIl 'kharrington' | xargs sed -i '' -e "s/kharrington/$USER/g"

echo "Parameters are $@"
#Run SLoeber
open $SLOBER_LOC/Eclipse.app --args "$@"
#$SLOBER_LOC/Eclipse.app/Contents/MacOS/eclipse "$@"
#open $SLOBER_LOC/Eclipse.app --args -import {"$@"}


